### ISSUE TITLE
compare two files

### ISSUE THREAD

**Issue by RusAlex** [Manwar/Test-Excel#1]
Im not yet good at perl , and cant understand easily how your software works. 

But I tried to run it on my files, and the result not obvious for me. Could you answer a questions.

1. Is it compare files cell by cell ? I saw this on my initial test files with just 2 rows and 2 columns. But when I tried on my little bigger files with 20 rows and 20 columns, your package always returned to me "Files identical" even when I change data in one cell in one file.

2. My files are very easy to compare, no formulas and not as big, just ~20 rows and ~20 and I do not want to write my own solution on languages I know better. More likely I will learn perl deeper if your package can help me. But in a description of it "It compares 2 files visuality" what is mean ? 

Thanks you.

**Comment by Manwar** [comment]
Hi,

I can explain you how this work but before that I would like to test why you are getting incorrect result. Therefore can you please send me your sample excel file (with 20 rows/20 columns) that failed your test?

Thanks for using my code.

Best Regards,
Mohammad S Anwar

**Comment by RusAlex** [comment]
Mailed to your @yahoo mail account.

Thanks

**Comment by Manwar** [comment]
Hi,

I have just pushed the patch to resolve the issue you raised as below (Test::Excel v1.30):

https://github.com/Manwar/Test-Excel/commit/46f19f76e198cc658720b492ea19f8a7cdc59f27

Hope this should solve the issue. Please let me know if you have any problem.

Many Thanks.

Best Regards,
Mohammad S Anwar

**Comment by Manwar** [comment]
Hi,
Thanks for sample files. I used my own sample files to re-create the issue at my end. It now works with your sample files as well.I have pushed another quick fix to the DEBUG field in (Test::Excel v1.31) as below:
https://github.com/Manwar/Test-Excel/commit/d69ff512f420a7e058b2d5abebb81c51918c6988

use strict; use warnings;use Test::Excel;
if (compare_excel("1.xls", "2.xls")) {   print "EXCELs are identical.\n";}else {   print "EXCELs are NOT identical.\n";}
Please refer to the documentation as the interface has slightly changed, to make it simple.
Best Regards,Mohammad S Anwar
"You can sometimes write faster code in C but you can always code faster in Perl." 

     On Saturday, 14 February 2015, 20:27, Alexander Pletnev <notifications@github.com> wrote:
   
 

 Mailed to your @yahoo mail account.

Thanks

**Comment by Manwar** [comment]
Hi Alexander,

I have made further changes and added two new methods to ease the use (Test::Excel v1.33).

https://github.com/Manwar/Test-Excel/commit/af94d12397dd8a386c798b6edacda75f7ebddf91

use strict; use warnings;
use Test::More;
use Test::Excel;

cmp_excel_ok("1.xls", "1.xls");
cmp_excel_not_ok("1.xls", "2.xls");

done_testing();

**Comment by RusAlex** [comment]
Here is the output of of last example 

```bash
no_plan takes no arguments at ./test.pl line 4.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
ok 1
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
Use of uninitialized value $iFnt in array element at  line 2621.
ok 2
1..2
The plan was already output at perl5/lib/perl5/Test/Builder.pm line 2510.
1..2
```

Suppose it still not compare them correctly.

**Comment by Manwar** [comment]
Except the warning, which is thrown by package outside of distribution, the  result is correct.

**Comment by RusAlex** [comment]
Ah yes, sorry noticed now that first test compares the same file. 

Do you plan to show at least positions of different cells? 

I remember, that when I first time run your software with simple files there was an output: 
```shell
BBB not equal to CCC
```

**Comment by Manwar** [comment]
Yes, you can get that if you set the environment variable DEBUG to 1.

**Comment by RusAlex** [comment]
Thank you very much for sorting my issue.

I will be using your package in my project. It will be first perl
dependency. But I suppose it's only a start.

Thanks

**Comment by Manwar** [comment]
Hi Alexander,

Just to let you know, I have disabled the warning thrown by the external package. Also documented the use of environment variable DEBUG. And added SYNOPSIS as well.

The updated package is Test::Excel v1.36

Best Regards,
Mohammad S Anwar
